version: "3.8"

services: 
  app:
    container_name: application_con
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
    volumes: 
      - .:/app
      - '/app/node_modules'
    depends_on: 
      - mysql_server
  
  mysql_server:
    image: mysql:8.0
    environment: 
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=thanhlam
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret

  phpmyadmin:
    container_name: phpadmin_con
    image: phpmyadmin:5.2.1
    restart: always
    ports:
    - 8081:80
    environment:
    - PMA_HOST=mysql_server
    - PMA_ARBITARY=1
    